// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm9qVYiKOjCcxOVMxriY9lKo5e32sJsZA',
    appId: '1:771271851509:web:74e4efb29cbe18e93d74bc',
    messagingSenderId: '771271851509',
    projectId: 'oneshield-5b406',
    authDomain: 'oneshield-5b406.firebaseapp.com',
    storageBucket: 'oneshield-5b406.appspot.com',
    measurementId: 'G-F2WJR9PR2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjs0BuGjynjsziha7R1KgAs5XVVdrHz5g',
    appId: '1:771271851509:android:3573e13ae7c4d7293d74bc',
    messagingSenderId: '771271851509',
    projectId: 'oneshield-5b406',
    storageBucket: 'oneshield-5b406.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApHJyZ6eBF0YtrSISoiCxZ8yPzsAA3bEs',
    appId: '1:771271851509:ios:449f896b31fae67f3d74bc',
    messagingSenderId: '771271851509',
    projectId: 'oneshield-5b406',
    storageBucket: 'oneshield-5b406.appspot.com',
    iosClientId: '771271851509-biv6f6aeoueat1ipckrriarceo5ogpei.apps.googleusercontent.com',
    iosBundleId: 'com.example.railways',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApHJyZ6eBF0YtrSISoiCxZ8yPzsAA3bEs',
    appId: '1:771271851509:ios:449f896b31fae67f3d74bc',
    messagingSenderId: '771271851509',
    projectId: 'oneshield-5b406',
    storageBucket: 'oneshield-5b406.appspot.com',
    iosClientId: '771271851509-biv6f6aeoueat1ipckrriarceo5ogpei.apps.googleusercontent.com',
    iosBundleId: 'com.example.railways',
  );
}
